import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Instrument_Sans } from "next/font/google";
import { Analytics as VercelAnalytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { Analytics } from "@/components/analytics";
import { FAQ, SITE } from "@/lib/content";
import "./globals.css";

const display = Instrument_Sans({
  variable: "--font-instrument",
  subsets: ["latin"],
  display: "swap",
});

const sans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const mono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const title = `${SITE.company}: ${SITE.tagline}`;

export const metadata: Metadata = {
  metadataBase: new URL(SITE.domain),
  title: {
    default: title,
    template: `%s | ${SITE.company}`,
  },
  description: SITE.description,
  applicationName: SITE.product,
  authors: [{ name: SITE.company, url: SITE.domain }],
  creator: SITE.company,
  publisher: SITE.company,
  category: "technology",
  /* Declared by hand from public/ rather than through the app/ file convention,
     for the two reasons the icon was missing from search results in the first
     place: the URLs stay clean and stable instead of carrying a build hash, and
     the theme-adaptive icon.svg is deliberately NOT declared. Google rasterises
     a favicon onto a white row, where that SVG's prefers-color-scheme stroke has
     nothing to hold on to. It stays on disk for anyone who wants it directly. */
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/favicon-48x48.png", sizes: "48x48", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-192x192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  alternates: { canonical: "/" },
  keywords: [
    // Brand.
    "Convalesce",
    "convalesce.io",
    // Core nouns.
    "data infrastructure",
    "data pipelines",
    "data workflows",
    "data warehouse",
    "data lakehouse",
    "data platform",
    "data orchestration",
    "data engineering",
    // The product.
    "self-healing",
    "self-healing data infrastructure",
    "self-healing data pipelines",
    "data pipeline automation",
    "pipeline failure recovery",
    "automated incident resolution",
    "pipeline monitoring",
    // Outcomes.
    "data observability",
    "data reliability",
    "data quality",
    "data downtime",
    "data incident response",
    // Mechanism.
    "data lineage",
    "blast radius analysis",
    "root cause analysis",
    "incident investigation",
    "schema drift",
    "schema drift detection",
    "evidence trail",
    // AI category.
    "AI agents for data",
    "agentic data engineering",
    "autonomous data operations",
    "AI data engineer",
    // Question keywords.
    "what is self-healing data infrastructure",
    "how to fix a failed data pipeline",
    "why did my data pipeline fail",
    "how to find the root cause of a pipeline failure",
    "what is blast radius in data",
    "how to detect schema drift",
    "data observability vs data quality",
    "how to make data pipelines self-healing",
    "how to automatically fix broken data pipelines",
    "how to reduce data pipeline failures",
    "how to trace data lineage after a failure",
    "how to find which dashboards a failed pipeline affects",
    "what is a self-healing data pipeline",
    "what is agentic data engineering",
    "what is data downtime",
    // Self-healing variants.
    "self healing",
    "self healing data pipelines",
    "self healing data infrastructure",
    "self-healing pipelines",
    "self-healing ETL",
    "self-healing ELT",
    "self-healing data platform",
    "self-healing data stack",
    "self-healing data warehouse",
    "self-healing data lake",
    "self-healing orchestration",
    "self-healing Airflow",
    "self-healing dbt",
    "self-healing Spark",
    "self-healing Snowflake",
    "self-healing Databricks",
    "self-healing BigQuery",
    "self-healing Kafka",
    "self-healing data quality",
    "self-healing infrastructure",
    "self-repairing data pipelines",
    "self-fixing data pipelines",
    "auto-healing data pipelines",
    "auto-remediation data pipelines",
    "automatic pipeline recovery",
    "autonomous pipeline repair",
    "automated pipeline remediation",
    "automated data pipeline fixes",
    "automated data pipeline troubleshooting",
    "pipeline auto-recovery",
    "pipeline self-recovery",
    "resilient data pipelines",
    "fault-tolerant data pipelines",
    "reliable data pipelines",
    // Failure and incident vocabulary.
    "failed pipeline",
    "failed DAG",
    "failed job",
    "failed run",
    "failed data job",
    "broken pipeline",
    "broken data pipeline",
    "pipeline failure",
    "pipeline failure analysis",
    "pipeline failure alerts",
    "pipeline incident",
    "pipeline outage",
    "pipeline debugging",
    "pipeline troubleshooting",
    "pipeline retry",
    "pipeline rollback",
    "pipeline remediation",
    "data pipeline errors",
    "data pipeline failures",
    "data pipeline reliability",
    "data pipeline resilience",
    "data pipeline recovery",
    "data pipeline debugging",
    "data pipeline troubleshooting",
    "data pipeline incident management",
    "data pipeline on-call",
    "data engineering on-call",
    "data on-call automation",
    "data incident management",
    "data incident postmortem",
    "data incident root cause",
    "data outage",
    "stale data",
    "missing data",
    "late data",
    "bad data",
    "data freshness",
    "data freshness monitoring",
    "data SLA",
    "data SLA monitoring",
    "data reliability engineering",
    "data downtime reduction",
    "mean time to resolution data",
    "mean time to detect data",
    "MTTR data pipelines",
    // Investigation and evidence.
    "automated root cause analysis",
    "root cause analysis for data pipelines",
    "AI root cause analysis",
    "failure investigation",
    "incident evidence",
    "evidence-backed fixes",
    "fix with evidence",
    "proposed fix pull request",
    "automated pull request fix",
    "blast radius",
    "downstream impact analysis",
    "impact analysis data",
    "column-level lineage",
    "table-level lineage",
    "end-to-end lineage",
    "lineage-aware incident response",
    "dependency graph data",
    "upstream failure",
    "downstream breakage",
    "schema change detection",
    "schema change impact",
    "schema evolution",
    "breaking schema changes",
    "data contract violations",
    "data contracts",
    "data drift",
    "anomaly detection data",
    "data anomaly detection",
    // AI and agents.
    "AI agents for data engineering",
    "AI agents for data pipelines",
    "AI for data operations",
    "AI for DataOps",
    "AI for data reliability",
    "AI data pipeline repair",
    "AI incident response",
    "AIOps for data",
    "agentic data operations",
    "agentic data pipelines",
    "agentic remediation",
    "LLM data pipeline debugging",
    "LLM agents data engineering",
    "autonomous data engineer",
    "autonomous data agents",
    "autonomous incident resolution",
    "AI on-call engineer",
    "AI data reliability engineer",
    // Category terms.
    "DataOps",
    "data operations",
    "data reliability engineering",
    "data observability platform",
    "data observability tool",
    "data observability tools",
    "data quality monitoring",
    "data pipeline monitoring",
    "data pipeline observability",
    "pipeline observability",
    "data monitoring",
    "data catalog",
    "metadata platform",
    "data governance",
    "data stack",
    "modern data stack",
    "data pipeline tools",
    "data engineering tools",
    "data engineering automation",
    "data workflow automation",
    "ETL monitoring",
    "ELT monitoring",
    "ETL automation",
    "ETL failure recovery",
    "workflow orchestration",
    "job orchestration",
    "orchestrator monitoring",
    // Alternatives and comparisons.
    "Monte Carlo alternative",
    "Datadog data observability alternative",
    "Bigeye alternative",
    "Acceldata alternative",
    "Metaplane alternative",
    "Anomalo alternative",
    "Great Expectations alternative",
    "Soda alternative",
    "data observability alternatives",
    "data observability vs monitoring",
    "data observability vs lineage",
    "data observability vs data catalog",
    "data observability vs AIOps",
    // Tools it connects to.
    "Airflow monitoring",
    "Airflow failure recovery",
    "Airflow DAG failure",
    "Airflow plugin",
    "Dagster monitoring",
    "Dagster plugin",
    "Prefect monitoring",
    "Prefect plugin",
    "dbt monitoring",
    "dbt test failures",
    "dbt model failures",
    "Spark monitoring",
    "Spark job failure",
    "Spark listener",
    "Snowflake monitoring",
    "Snowflake query history",
    "Databricks monitoring",
    "Databricks job failure",
    "BigQuery monitoring",
    "BigQuery job failure",
    "Postgres monitoring",
    "Kafka monitoring",
    "Kafka consumer lag",
    "AWS Glue monitoring",
    "AWS Glue job failure",
    "Amazon S3 data",
    "Google Cloud Storage data",
    "Dataplex",
    "Vertex AI pipelines",
    "Looker dashboards",
    "Tableau dashboards",
    "Fivetran sync failure",
    "Great Expectations checks",
    "GitHub pull requests data",
    "OpenLineage",
    "OpenLineage integration",
    // Product and audience.
    "data engineers",
    "analytics engineers",
    "data platform teams",
    "data teams",
    "data leaders",
    "startup data stack",
    "enterprise data reliability",
    // More self-healing phrasing.
    "self-healing software",
    "self-healing systems",
    "self-healing data systems",
    "self-healing data engineering",
    "self-healing data operations",
    "self-healing DataOps",
    "self-healing data workflows",
    "self-healing jobs",
    "self-healing DAGs",
    "self-healing batch jobs",
    "self-healing streaming pipelines",
    "self-healing data quality checks",
    "self-healing dashboards",
    "self-healing analytics",
    "self-healing AI pipelines",
    "self-healing ML pipelines",
    "self-healing MLOps",
    "self-healing lineage",
    "self-healing with evidence",
    "self-healing agents",
    "self-healing platform",
    "self-healing automation",
    "self-healing cloud data",
    "self-healing Dagster",
    "self-healing Prefect",
    "self-healing Kafka pipelines",
    "self-healing Great Expectations",
    "self-healing Fivetran",
    "self-healing AWS Glue",
    "self-healing Postgres",
    "self-healing Looker",
    "self-healing Tableau",
    "self-healing GitHub workflow",
    "self healing pipelines",
    "self healing ETL",
    "self healing data platform",
    "self healing infrastructure",
    "self healing AI",
    "selfhealing data",
    "healing data pipelines",
    "heal data pipelines",
    "heal failed pipelines",
    "heal broken data",
    "data pipeline healing",
    "data healing",
    "convalescence data",
    "pipeline recovery automation",
    "pipeline repair automation",
    "automatic data repair",
    "automatic data fixes",
    "automatic root cause",
    "auto-fix data pipelines",
    "auto-fix failed jobs",
    "auto-retry failed pipelines",
    "automated retries",
    "automated backfill",
    "automated backfills",
    "backfill data pipelines",
    "backfill after failure",
    "rerun failed pipeline",
    "rerun failed DAG",
    "replay failed run",
    "restart failed job",
    "recover failed run",
    "resume failed pipeline",
    // More failure causes.
    "schema mismatch",
    "column renamed",
    "column dropped",
    "type change",
    "null values pipeline",
    "duplicate rows",
    "row count drop",
    "volume anomaly",
    "freshness anomaly",
    "distribution drift",
    "upstream API change",
    "source system change",
    "permission denied pipeline",
    "credentials expired",
    "API rate limit",
    "timeout error",
    "out of memory Spark",
    "out of memory job",
    "disk full",
    "dependency failure",
    "dependency version conflict",
    "config change",
    "deploy broke pipeline",
    "bad commit",
    "bad deploy",
    "failed migration",
    "failed merge",
    "failed load",
    "failed transformation",
    "failed ingestion",
    "failed extract",
    "failed sync",
    "failed test",
    "failed data test",
    "failed check",
    "failed expectation",
    "failed model",
    "failed task",
    "failed query",
    "failed stream",
    // More mechanism and evidence.
    "incident timeline",
    "incident summary",
    "incident report",
    "incident evidence trail",
    "incident triage",
    "incident triage automation",
    "alert triage",
    "alert fatigue data",
    "alert noise reduction",
    "alert grouping",
    "alert correlation",
    "event correlation",
    "change log analysis",
    "change tracking data",
    "run history",
    "run metadata",
    "job metadata",
    "pipeline metadata",
    "operational metadata",
    "execution metadata",
    "lineage graph",
    "lineage events",
    "lineage tracking",
    "lineage visualization",
    "lineage for incidents",
    "dataset lineage",
    "job lineage",
    "impact radius",
    "affected tables",
    "affected dashboards",
    "affected consumers",
    "affected owners",
    "who is affected by a pipeline failure",
    "which tables are affected",
    "which dashboards are broken",
    "owner notification",
    "stakeholder notification",
    "incident ownership",
    "data ownership",
    "data owners",
    // More question keywords.
    "how to automate data pipeline recovery",
    "how to reduce data downtime",
    "how to reduce MTTR for data incidents",
    "how to debug a failed Airflow DAG",
    "how to debug a failed dbt run",
    "how to debug a failed Spark job",
    "how to debug a failed Dagster run",
    "how to debug a failed Prefect flow",
    "how to debug a failed Databricks job",
    "how to fix schema drift",
    "how to handle schema changes in pipelines",
    "how to find affected dashboards",
    "how to monitor data pipelines",
    "how to monitor Airflow",
    "how to monitor dbt",
    "how to monitor Spark",
    "how to build reliable data pipelines",
    "how to make pipelines resilient",
    "how to automate on-call for data teams",
    "how to use AI for data engineering",
    "how to use AI agents for pipelines",
    "why do data pipelines fail",
    "why do dbt models fail",
    "why do Airflow DAGs fail",
    "why do Spark jobs fail",
    "what causes data downtime",
    "what is a data incident",
    "what is pipeline observability",
    "what is data reliability engineering",
    "what is DataOps",
    "what is root cause analysis in data engineering",
    "what is lineage-aware incident response",
    "best tools for data pipeline recovery",
    "best data observability tools",
    "best AI tools for data engineers",
    "is there a self-healing data tool",
    "self-healing data tools",
    "self-healing data software",
    "self-healing data pipeline tools",
    "self-healing data pipeline software",
    "self-healing data pipeline platform",
    "self-healing data pipeline examples",
    "self-healing data pipeline architecture",
    "self-healing data pipeline AI",
    "self-healing pipeline guide",
    // Buying and trial intent.
    "free data observability",
    "free data pipeline monitoring",
    "free self-healing tool",
    "try self-healing data infrastructure",
    "get started self-healing data",
    "data observability for startups",
    "data observability for small teams",
    "data observability pricing",
    "data observability open source",
    "GDPR data processor",
  ],
  openGraph: {
    title,
    description: SITE.description,
    url: SITE.domain,
    siteName: SITE.company,
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description: SITE.description,
  },
  /* index+follow is the crawler default, so stating it here only duplicates
     the tag Next emits on /404. Only the googleBot extensions earn their tag. */
  robots: {
    googleBot: {
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
  colorScheme: "dark",
};

/* One graph, four entities: who we are, the site, the product, and the FAQ.
   Each node is addressable by id so crawlers can connect them. */
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE.domain}/#org`,
      name: SITE.company,
      url: SITE.domain,
      description: SITE.description,
      /* Google's logo guidance wants dimensions it can trust, not a bare URL. */
      logo: {
        "@type": "ImageObject",
        "@id": `${SITE.domain}/#logo`,
        url: `${SITE.domain}/favicon-512x512.png`,
        width: 512,
        height: 512,
        caption: SITE.company,
      },
      image: { "@id": `${SITE.domain}/#logo` },
      email: SITE.email,
      contactPoint: [
        {
          "@type": "ContactPoint",
          contactType: "customer support",
          email: SITE.email,
          availableLanguage: "English",
        },
        {
          "@type": "ContactPoint",
          contactType: "data protection",
          email: SITE.privacyEmail,
          availableLanguage: "English",
        },
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE.domain}/#site`,
      url: SITE.domain,
      name: SITE.company,
      alternateName: "convalesce.io",
      description: SITE.description,
      publisher: { "@id": `${SITE.domain}/#org` },
      inLanguage: "en",
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE.domain}/#product`,
      name: SITE.product,
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Cloud",
      description: SITE.description,
      url: SITE.domain,
      author: { "@id": `${SITE.domain}/#org` },
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
        availability: "https://schema.org/InStock",
        url: `${SITE.domain}/#top`,
      },
    },
    {
      "@type": "FAQPage",
      "@id": `${SITE.domain}/#faq`,
      mainEntity: FAQ.map((item) => ({
        "@type": "Question",
        name: item.q,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${display.variable} ${sans.variable} ${mono.variable} h-full antialiased`}
    >
      <head>
        {/* The site is dark by design; Dark Reader would re-invert it into mush.
            Next drops a metadata `other` entry whose value is an empty string,
            so this one has to be a real tag. */}
        <meta name="darkreader-lock" />
      </head>
      {/* Browser extensions (a grammar checker, a password manager) write their
          own attributes onto <body> before React loads. Those are not ours to
          match, so a difference on this one element is not reported. */}
      <body className="bg-bg text-ink min-h-full" suppressHydrationWarning>
        {children}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <VercelAnalytics />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
